name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linting (flake8)
        run: |
          pip install flake8
          flake8 app/ tests/

      - name: Run Unit Tests
        run: |
          pip install pytest
          pytest tests/

      - name: Notify on Failure
        if: failure()
        run: echo "❌ Build failed. Please check the logs."
